- Conversations
  - Topics
    - Topic: Daily Life
      - Conversation
        - ID: 1
        - Topic Tag: Polite Introduction and Asking for Directions
        - Passages:
          - Passage 1:
            - ID: 1
            - Person Speaking: Stranger
            - English Text: "Hey, excuse me, can I ask you something?"
            - English Text in Spanish word order: "Hey, excuse me, can I ask something to you?"
            - Spanish Text: "Hola, disculpe, ¿puedo preguntarle algo?"
            - Spanish text in English word order: "Hola, disculpe, ¿puedo preguntarle algo a usted?"
            - English Audio file: "passage1_en.mp3"
            - Spanish Audio file: "passage1_es.mp3"
            - Words:
              - Word: ["Hey"] | Start time: 0 | End time: 300 (milliseconds)
              - Word: ["excuse me"] | Start time: 300 | End time: 600
              - Word: ["can I"] | Start time: 600 | End time: 900
              - Word: ["ask you"] | Start time: 900 | End time: 1200
              - Word: ["something"] | Start time: 1200 | End time: 1500

          - Passage 2:
            - ID: 2
            - Person Speaking: Reader (You)
            - English Text: "Of course! What do you need help with?"
            - English Text in Spanish word order: "Of course! With what do you need help?"
            - Spanish Text: "¡Por supuesto! ¿Con qué necesita ayuda?"
            - Spanish text in English word order: "¡Por supuesto! ¿Qué necesita ayuda con?"
            - English Audio file: "passage2_en.mp3"
            - Spanish Audio file: "passage2_es.mp3"
            - Words:
              - Word: ["Of"] | Start time: 0 | End time: 100
              - Word: ["course"] | Start time: 100 | End time: 300
              - Word: ["What"] | Start time: 300 | End time: 400
              - Word: ["do you"] | Start time: 400 | End time: 600
              - Word: ["need help"] | Start time: 600 | End time: 900
              - Word: ["with"] | Start time: 900 | End time: 1100

          - Passage 3:
            - ID: 3
            - Person Speaking: Stranger
            - English Text: "Could you tell me where the nearest subway station is?"
            - English Text in Spanish word order: "Could you tell me where the subway station nearest is?"
            - Spanish Text: "¿Podría decirme dónde está la estación de metro más cercana?"
            - Spanish text in English word order: "¿Podría decirme dónde está la estación de metro más cercana?"
            - English Audio file: "passage3_en.mp3"
            - Spanish Audio file: "passage3_es.mp3"
            - Words:
              - Word: ["Could"] | Start time: 0 | End time: 200
              - Word: ["you"] | Start time: 200 | End time: 400
              - Word: ["tell me"] | Start time: 400 | End time: 800
              - Word: ["where"] | Start time: 800 | End time: 1000
              - Word: ["nearest subway station"] | Start time: 1000 | End time: 1400
              - Word: ["is"] | Start time: 1400 | End time: 1500

          - Passage 4:
            - ID: 4
            - Person Speaking: Reader (You)
            - English Text: "It's just down the street, two blocks ahead."
            - English Text in Spanish word order: "It is just down the street, two blocks ahead."
            - Spanish Text: "Está justo al final de la calle, dos cuadras adelante."
            - Spanish text in English word order: "Está justo abajo de la calle, dos cuadras adelante."
            - English Audio file: "passage4_en.mp3"
            - Spanish Audio file: "passage4_es.mp3"
            - Words:
              - Word: ["It is"] | Start time: 0 | End time: 200
              - Word: ["just"] | Start time: 200 | End time: 400
              - Word: ["down the street"] | Start time: 400 | End time: 800
              - Word: ["two blocks"] | Start time: 800 | End time: 1000
              - Word: ["ahead"] | Start time: 1000 | End time: 1200

          - Passage 5:
            - ID: 5
            - Person Speaking: Stranger
            - English Text: "Thank you so much! Have a great day!"
            - English Text in Spanish word order: "That you have a great day!"
            - Spanish Text: "¡Muchas gracias! ¡Que tenga un buen día!"
            - Spanish text in English word order: "¡Muchas gracias! ¡Que usted tenga un buen día!"
            - English Audio file: "passage5_en.mp3"
            - Spanish Audio file: "passage5_es.mp3"
            - Words:
              - Word: ["Thank you"] | Start time: 0 | End time: 400
              - Word: ["so much"] | Start time: 400 | End time: 700
              - Word: ["Have"] | Start time: 700 | End time: 900
              - Word: ["a great day"] | Start time: 900 | End time: 1200
